---
- name: Random line from file
  hosts: all
  tasks:
    - name: Count lines in file
      register: line_count
      ansible.builtin.shell: wc -l csx.csv | awk '{print $1}'
      changed_when: false

    - name: Random number
      ansible.builtin.set_fact:
        random_number: "{{ line_count.stdout | random }}"

    - name: Print line at random index
      ansible.builtin.shell: head -n {{ random_number }} csx.csv | tail -n 1
      changed_when: false
