---
- name: Perform a line count on a file named 'names.csv' and print a random number in that range.
  hosts: all
  gather_facts: false
  tasks:
    - name: Count lines in file
      register: wc_output
      ansible.builtin.shell: wc -l /home/ryariley/csx-expo/names.csv | awk '{print $1}'

    - name: Convert to Int
      ansible.builtin.set_fact:
        count: "{{ wc_output | int }}"

    - name: Print random number in range
      ansible.builtin.debug:
        msg: "{{ wc_output.stdout | random }}"
